const getMissingRouteError = (path) => ({
  response: {
    status: 404,
    statusText: `mock route path for ${path} does not exist`,
  },
});

export const successfulResponse = {
  statusText: 'OK',
  status: 200,
};
export const mockEmails = [
  {
    data: [
      {
        id: 1,
        primary: 'Brunch this week?',
        secondary:
          "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: 'Sundar Pichai',
      },
      {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
                anniversary. I am really confused & would love your thoughts on it.`,
        person: 'Moulte Prod',
      },
      {
        id: 3,
        primary: 'Recipe to try',
        secondary:
          'I am try out this new BBQ recipe, I think this might be amazing',
        person: 'Mom',
      },
      {
        id: 4,
        primary: 'Yes',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: 'Customer Service',
      },
      {
        id: 5,
        primary: "Doctor's Appointment",
        secondary:
          'My appointment for the doctor was rescheduled for next Saturday.',
        person: 'Doctor',
      },
      {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
                navigation drawer or overflow menu) open as bottom sheets at a higher elevation
                than the bar.`,
        person: 'Manager',
      },
      {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
                for my backyard and would love to fire up the grill.`,
        person: 'Advertiser',
      },
    ],
  },
];

const loadEmails = () => mockEmails;

const wait = (delay) => new Promise((resolve) => setTimeout(resolve, delay));

const requestHandler = () => async (path, body, options) => {
  const routes = [{ regex: /^getEmails$/, controller: loadEmails }];
  const route = routes.find((mockRoute) => mockRoute.regex.test(path));
  if (!route || !route.controller) {
    throw getMissingRouteError(path);
  }
  const pathNames = path.split('/');
  const { controller } = route;
  const response = {
    ...successfulResponse,
    data: controller({ pathNames, body, options }),
  };
  await wait(500);
  return response;
};

export default {
  post: requestHandler(),
  get: requestHandler(),
};
